#!/usr/bin/env bash
# This script configures Nginx for custom 404 page

# Install nginx
apt-get update
apt-get install -y nginx

# Create a backup of the original default configuration
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name _;
        location / {
					try_files \$uri \$uri/ =404;
		}
		error_page 404 /404.html;
		location  /404.html {
			internal;
		}

		if (\$request_filename ~ redirect_me){
			rewrite ^ http://innovateweb.tech permanent;
		}
}
"
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$config" > /etc/nginx/sites-available/default

service nginx restart
