#!/usr/bin/env bash
# Install and configure HAProxy to handle requests for web-01 and web-02 servers
sudo apt-get update
sudo apt-get install -y haproxy

# Make a backup file for the default configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend load_balancer
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 225693-web-01 54.172.10.28:80 check
    server 225693-web-02 52.207.78.7:80 check
EOF

# Ensure HAProxy can be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy
sudo systemctl restart haproxy
