#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name, of
#+ processes whose name contain the word bash

pids=$(pgrep -f bash)
for pid in $pids
do
	if [ -f "/proc/$pid/cmdline" ]
	then
		pid_name=$(tr -d '\0' < "/proc/$pid/cmdline")
		echo "$pid $pid_name"
	fi
done
