#!/usr/bin/env bash
# Bash script that displays:
# "To infinity and beyond" indefinitely
# With a sleep 2 in between each iteration
# It also displays "I am invincible!!!" when receiving a SIGTERM signal
# The script will get killed with the script 67-stop_me_if_you_can

# Function to handle SIGTERM signal
terminate()
{
  echo "I am invincible!!!"
  exit 0
}

# Register the terminate function to handle SIGTERM signal
trap terminate SIGTERM

while true; do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
