#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
#+ It display only username, user id and Home directory path for the user

file="/etc/passwd"
while separator=: read -r username _ uid _ _ home _
do
	echo "$username$uid$home"
done < "$file"
