#!/usr/bin/env bash
# A script that prints Best School 10 times using while loop
#+ But for the 9th iteration, displays Best School and then Hi on a new line
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
