#!/usr/bin/env bash
# A script that prints Best School 10 times using while loop
#+ But for the 4th iteration, displays bad luck on a new line and
#+ For the 8th iteration, displays good luck
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
