#!/usr/bin/env bash
# A script that prints numbers from 1 to 20 using while loop
#+ But for the 4th iteration, displays bad luck from China after displaying 4
#+ For the 9th iteration, displays bad luck from Japan after displaying 9
#+ For the 17th iteration, displays bad luck from Italy after displaying 17
i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	i=$((i+1))
done
