#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes using while loop
#+ Displays hours from 0 to 12
#+ Displays minutes from 1 to 59
hour=0
echo "Hour: $hour"
while [ $hour -lt 13 ]
do
	i=1
	while [ $i -le 59 ]
	do
		echo "$i"
		i=$((i+1))
	done
	hour=$((hour+1))
	if [ $hour -lt 13 ]
	then
		echo "Hour: $hour"
	fi
done

