#!/usr/bin/env bash
# A bash script that displays :
#+ The content of the current directory in a list format using for loop
#+ Where only the part of the name after the first dash is displayed
for file in *;
do
	if [[ -f "$file" && ! "$file" == .* ]];
	then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
