#!/usr/bin/env bash
# A Bash script that gives information about the school file. using if and, else
# If the file exists prints: school file exists
# If the file does not exist prints: school file does not exist
# If the file exists, print:
# If the file is empty: school file is empty
# If the file is not empty: school file is not empty
# If the file is a regular file: school is a regular file
# If the file is not a regular file: (nothing)

file="school"
if [ -e "$file" ]
then
	echo "school file exists"
else
	echo "school file does not exist"
fi

if [ -e "$file" ]
then
	if [ -s "$file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
fi
