#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user, listen on all 
#+ active IPs on port 8080.

# Install nginx if not already installed
if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install -y nginx
fi

# Stop nginx if it's already running
systemctl stop nginx

# Configure nginx to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Start nginx
systemctl start nginx
