#!/usr/bin/env bash
# This script accepts one argument, which should be a username.
# It runs the 'whoami' command under the user passed as an argument.

# Run whoami as the specified user
sudo -u "$1" whoami
